### ISSUE TITLE
The forget me action leads to a blank screen

### ISSUE THREAD

**Issue by jaapjansma** [eileenmcnaughton/org.wikimedia.forgetme#1]
When I go to contact summary and press actions Forget Me it leads to an empty screen. See below for the screen shot
![2022-05-30_17-23](https://user-images.githubusercontent.com/4126292/171022753-7683f240-e368-415e-aa42-fb80a403e526.png)

**Comment by eileenmcnaughton** [comment]
@jaapjansma any js errors? It can be a little slow to load too...

**Comment by jaapjansma** [comment]
No no errors. Or no 404 errors in loading the JS. I cleared the civicrm caches and drupal caches but no effect.

**Comment by eileenmcnaughton** [comment]
hmm - it calls the apiv3 action `Contact.showme`

**Comment by eileenmcnaughton** [comment]
& then `Contact.forgetme` - when a button is clicked

**Comment by jaapjansma** [comment]
What do you mean? It does not work as said and no errors. I dont see why I should call the api. It is not a big deal for me as I was trying this one out the Anonymize extension form systopia. And I decided to try to use anonymize for the use case I am working on.

**Comment by eileenmcnaughton** [comment]
@jaapjansma that's fine - what I see on the screen is this - I can't recall why I didn't use the Systopia one - there was a gap but I don't recall what it was

![image](https://user-images.githubusercontent.com/336308/171058615-fb556987-1056-4175-8188-d3d5842e3126.png)
![image](https://user-images.githubusercontent.com/336308/171058643-c9580f11-5462-48d6-9d72-c17ada3c959d.png)
